### ISSUE TITLE
Poladit přehazovací algoritmus

### ISSUE THREAD

**Issue by VlastaKoudelka** [neuropacabra/FrequencyTagger#2]
detekce polarity TAG kanálu vždy prohodí polaritu (maximum je vždy větší než průměr signálu)

**Comment by neuropacabra** [comment]
Chápu správně, že tohle je vyřešené?

`% Decide if its positive or negative peaks
if mean(EEGData(:,indTAG)) < max(EEGData(:,indTAG))
    EEGData(:,indTAG) = -EEGData(:,indTAG);
end`

**Comment by VlastaKoudelka** [comment]
Právě že není, protože ten signál bude mít vždycky větší maximum než je jeho střední hodnota (kromě konstantního signálu), takže to převrací pokaždé. Vzal jsem řešení z jednoho detektoru ECG, to mi příjde dobré:

```matlab
if prctile(EEGData(:,indTAG),1)+prctile(EEGData(:,indTAG),99)<0
      EEGData(:,indTAG) = -EEGData(:,indTAG);
end

**Comment by VlastaKoudelka** [comment]
To vlastně testuje na kterou stranu je sešikmená distribuce našeho TAG signálu
